name: Trigger auto deployment for nivi-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nivi-container-app-AutoDeployTrigger-33ba3bd1-4578-4db9-8c1c-fd4c450fa856.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NIVICONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: nivicontainer.azurecr.io
          registryUsername: ${{ secrets.NIVICONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NIVICONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: nivi-container-app
          resourceGroup: siemens-nivi-rg-my-container-apps
          imageToBuild: nivicontainer.azurecr.io/nivi-container-app:${{ github.sha }}
          
            

     

